### ISSUE TITLE
Can't pickle/unpickle composite Maps

### ISSUE THREAD

**Issue by slandelle** [ochrons/boopickle#10]
Hi Otto,

Trying to pickle and unpickle composites such as `Map[String, Map[String, Int]]` doesn't compile.

The workaround I currently use is to wrap the values into a case class like `case class MapWrapper(map:  Map[String, Int])` and then I can use `Map[String, MapWrapper]` but that's cumbersome.

Advice?

**Comment by ochrons** [comment]
I added a test case like below and it compiles and works just fine. Any ideas what's the difference to your codebase?

```scala
val testMap = Map[String, Map[String, Int]]("test" -> Map[String, Int]("test2" -> 5))
val bb = Pickle.intoBytes(testMap)
assert(Unpickle[Map[String, Map[String, Int]]].fromBytes(bb) == testMap)
```

**Comment by slandelle** [comment]
Here's a sample that doesn't compile:

```scala
import boopickle._

case class Foo(bar: Map[String, Bar])
case class Bar(baz: Baz)
case class Baz(map: Map[String, Map[String, Int]])

val data: Foo = ???
Pickle.intoBytes(data)
```

**Comment by ochrons** [comment]
Feels like a problem in how scalac recurses those types. As a workaround you can define a custom pickler for your class to simplify it for the compiler.

**Comment by slandelle** [comment]
Sure, I could do that. Or wrap the `Map[String, Int]` with a case class so types are properly sorted out.
But it's just sad I can't be lazy like everywhere else ;-)

**Comment by ochrons** [comment]
Looks like the compiler cannot resolve the implicits in a reliable way in this case, so you'll need to provide a custom pickler. Or perhaps providing more explicit implicits (!) would be enough. In either case, not something the library can solve for you, unfortunately.

```
boopickle.this.Pickler.mapPickler is not a valid implicit value for boopickle.Pickler[Map[String,Baz]] because: [info] hasMatchingSymbol reported error: diverging implicit expansion for type boopickle.Pickler[Map[String,List[String]]]
```

**Comment by slandelle** [comment]
Is this something that should be reported to the scala compiler team?

**Comment by ochrons** [comment]
Probably not as it's a well known issue with implicits.

**Comment by slandelle** [comment]
OK, thanks
