### ISSUE TITLE
Automatigically handled sealed traits whose implementations are case classes

### ISSUE THREAD

**Issue by slandelle** [ochrons/boopickle#13]
@ochrons You told me to keep ideas coming, so here's one.

I'll be honest: this is out of my reach and I wouldn't be able to contribute it, so I'll perfectly understand if you decide ditch it.

Quite often, I have some sealed abstraction (trait or abstract class) where all the implementations are case classes. Currently, I have to write Picklers and Unpicklers all the way down to deal with the abstractions, which is simple yet boilerplate.

With macros, it's possible to enumerate the implementations of a sealed trait, here's an [example](https://github.com/d6y/enumeration-examples/blob/master/macros/src/main/scala/EnumerationMacros.scala). So, based on this, it could maybe be possible for Boopickle to automatically generate the Picklers and Unpicklers implementations for such hierarchy.

**Comment by ochrons** [comment]
Yeah, this is how uPickle does it, but it doesn't always work and produces weird problems and compiler errors. Doesn't the CompositePickler work for you in these cases?

**Comment by slandelle** [comment]
Thanks, `CompositePickler` mostly did the trick, sorry for the noise.

The only limitation I found is that I sometimes had to explicitly expose the CompositePickler's pickler and unpickler for types that are deep in the tree. Still trying to figure out a simple test case.
