### ISSUE TITLE
Initial size padding

### ISSUE THREAD

**Issue by AlexLourenco** [ochrons/boopickle#14]
Hello there,

I have been looking through the code and documentation trying to figure out if there's a method to shave off the initial buffer (which allocates to the default size of 1400) after Pickling an element.

My current solution is just to extract the native ArrayBuffer and just splice before sending it across the wire like so:

      def send(message: Message) = {
		val pickled = Pickle.intoBytes(message)
		val typedBuffer = new TypedArrayBufferOps(pickled).arrayBuffer()

		ws.send(typedBuffer.slice(0, pickled.limit))
	}

While it's not too much work, since its possible to Pickle Sequence and other container alike data structures in a single command, technically there shouldn't be any mutations to be applied to the buffer. Is there some other reason for this design choice?

Thanks for reading and apologies in advanced if this isn't considered an issue =)

**Comment by ochrons** [comment]
That's the way ByteBuffers work. They maintain an internal state of how much of the buffer is actually used. Trimming the created ByteBuffer would require additional copying.

Scala-js-dom 0.8.1 supports sending ByteBuffers over Ajax post using the following code

```scala
    implicit def byteBuffer2ajax(data: ByteBuffer): InputData = {
      if (data.hasTypedArray()) {
        // get relevant part of the underlying typed array
        data.typedArray().subarray(data.position, data.limit)
      } else {
        // fall back to copying the data
        val tempBuffer = ByteBuffer.allocateDirect(data.remaining)
        val origPosition = data.position
        tempBuffer.put(data)
        data.position(origPosition)
        tempBuffer.typedArray()
      }
    }
```

Suppose I need to update the documentation to clarify how to use ByteBuffers :)
