### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by prettynatty** [ochrons/boopickle#16]
Would be great to have the ability to specify field tags to let server speak to let server speak to old clients, like this:
```
case class Message(@tag(0) field1, @deprecated @tag(1) field2, @tag(2) field3)
```
Fields marked as `@deprecated` should be read (if present in bytes) but never written.

**Comment by ochrons** [comment]
Yes, this is indeed worth investigating. Just have to be careful not to unnecessarily bloat encoding of case classes that do not use annotations.

**Comment by prettynatty** [comment]
There is also one thing about using `@deprecated` annotation. It may cause problems when using `-Xfatal-warnings` options because scala's `@deprecated` produces a warning.
There is such functionality in Kryo, but it uses Java's `@Deprecated` annotation, and doesn't produce any warnings when compiling scala code.

**Comment by ochrons** [comment]
Ok, good to know. I can always define my own annotations to be used for this case, so this would not become a problem.

**Comment by ochrons** [comment]
Closing this as it's not really feasible given the volatile nature of BooPickle coding.
