### ISSUE TITLE
Compile error when using boopickle with a project that uses scalac "-Xstrict-inference"

### ISSUE THREAD

**Issue by ngbinh** [ochrons/boopickle#17]
When include boopickle 1.0.0 and turn on `"-Xstrict-inference"`, this line:

```scala
case class A(s: String)
data: A = A("a")
Pickle.intoBytes(data)
```

will fail with this error message:
```scala
type mismatch;
[error]  found   : Some[A]
[error]  required: Option[Int]
[error]  Pickle.intoBytes(data)
```

I believe the macro generated by boopickle might contains code that cannot pass through `"-Xstrict-inference"`.

**Comment by ngbinh** [comment]
One solution is to enable the check `"-Xstrict-inference"` when building boopickle. I can work on that PR if you think the approach is sound. 

Keep in mind that with `"-Xstrict-inference"`, 

You cant do this
```scala
opt match {
  case Some(a) => foo(a)
  case None => bar
}
```

anymore but

```scala
opt map foo getOrElse bar
```

**Comment by ochrons** [comment]
I suppose this piece is the "offending" one.
```scala
          state.identityRefFor(value) match {
            case Some(idx) =>
              state.enc.writeInt(-idx)
            case None =>
              state.enc.writeInt(0)
```

But is that `strict-inference` option really used that much to make it worthwhile updating the generated code?

**Comment by ngbinh** [comment]
Not too sure about its popularity but without the fix, I cannot use boopickle due to the compile error.

**Comment by ngbinh** [comment]
I could work on a PR for this but I am not sure if this is the approach you'd like to take.

**Comment by ochrons** [comment]
If it's a simple fix, then a PR is most welcome :)

**Comment by ngbinh** [comment]
ok, I will work on a PR. It is not hard, just have to change the style so loosely match like 
```scala
opt match {
  case Some(a) => foo(a)
  case None => bar
}
```

is not allowed anymore.

**Comment by japgolly** [comment]
@ngbinh @ochrons  Jason Zaugg says:

> I would recommend against using -Xstrict-inference as it isn't finished:

https://groups.google.com/d/msg/scala-user/LTZxbpZ7o-E/YX4fq4npo08J

**Comment by ngbinh** [comment]
@japgolly thanks mate!
