### ISSUE TITLE
Opt-out or disable automatic codecs by macro

### ISSUE THREAD

**Issue by japgolly** [ochrons/boopickle#18]
You mention performance side-effects of codecs generated automatically by macro here:
https://github.com/ochrons/boopickle#automatic-generation-of-hierarchy-picklers

I'd really like a way to opt-out, or disable `MaterializePicklerFallback`, so that I can be sure that I'm using   `val`s without accidently missing cases.

**Comment by slandelle** [comment]
I think current design would let you opt out the fallbacks compile-time. But you can probably override them so the replacement crashes at runtime.

**Comment by japgolly** [comment]
`Pickler` inherits `MaterializePicklerFallback` which adds the macro to the implicits search path. I don't see how a library user can avoid it. (That it is on the implicits search path is a compiler-time concern - nothing to do with runtime.)

**Comment by ochrons** [comment]
So perhaps moving the pickler implicits into a trait and providing two versions for importing would work ok?

**Comment by ochrons** [comment]
BTW, do you mean opting out of case class pickler generation altogether, or just for class hierarchies?

**Comment by slandelle** [comment]
@japgolly I meant trying to provide another fallback implementation that would be picked compile time instead of the regular ones and that would throw an exception at runtime. Just an ugly workaround I agree.

**Comment by japgolly** [comment]
@ochrons I'd like to be able to opt-out of any dynamic codecs (so any `implicit defs`), including case class gen. I'd still like to *use* the case class & sealed heirarchy generators via manual calls - I just need to be able to avoid the `implicit` part.

> So perhaps moving the pickler implicits into a trait and providing two versions for importing would work ok?

That'd be perfect & appreciated! When looking for Scala searches your namespace, companion objects (so inside `object Pickler` for any `Pickler[X]`), and alongside the class/trait. The namespace is the only one a library user has control over. Otherwise :+1: 

@slandelle Yeah agree. I like compiler errors for these things :)

**Comment by japgolly** [comment]
A suggestion: Currently the README instructs users to `import boopickle._`. A nice idea might be to have no implicits anywhere, then create an `object Default`, and put all the out-of-the-box implicits in there as references to the non-implicit implementations, and even type alises like `scala.Predef` does. Then users still get a nice, easy one-liner (`import boopickle.Default._`) and others like me can pick apart what we need.

Something like:
```scala
object Default {
  // Like what scala.Prefef does with String et al
  type Pickler[A] = _root_.boopickle.Pickler[A]
  val Pickler = _root_.boopickle.Pickler

  implicit def stringPickler: Pickler[String] = Pickler.stringPickler
  ...
}
```

Just an idea...

**Comment by ochrons** [comment]
Yeah, I was looking into this and it seems there is no way to get this done without breaking backwards compatibility on the `import`. But that's not a big issue, if it just involves changing that one import.

**Comment by ochrons** [comment]
I made a branch with these changes at https://github.com/ochrons/boopickle/tree/opt_implicits

The implicits are futher divided into traits (combined by `Default`) so you can also pick and choose what you want.

Please check it out and comment if it works ok.

**Comment by japgolly** [comment]
Awesome, thanks, the change is appreciated. I'll see if I get an opportunity to give this a try over the weekend.
