### ISSUE TITLE
Type Parameters of sealed Traits are not forwarded correctly

### ISSUE THREAD

**Issue by FlorianKirmaier** [ochrons/boopickle#23]
This bug is similar too #22

When a Unpickler is generated for a Trait, then the Type Arguments are not correctly forwarded to the Sub-Types.

File1
```scala
  sealed trait A1Trait[T]
  case class A1[T](i: Double) extends A1Trait[T]
```
File2 (because of SI-7046)
```scala
boopickle.Unpickler.materializeUnpickler[A1Trait[Int]]
```
compileroutput (with boopickler 1.0.1-SNAPSHOT):
```
[error] C:\Users\florian.kirmaier\Dropbox\git\File2.scala:31: cla
ss A1 takes type parameters
[error]   val Bunpickler = boopickle.Unpickler.materializeUnpickler[A1Trait[Int]]
[error]                                                            ^
[error] one error found
[error] (scalaServer/compile:compile) Compilation failed
[error] Total time: 23 s, completed Jun 23, 2015 7:14:11 PM
```
The function materializeUnpickler generates the following AST:
```scala
result: Expr[boopickle.Unpickler[A1Trait[Int]]]({
  implicit object TraitUnpickler$macro$1 extends boopickle.CompositeUnpickler[A1Trait[Int
]] {
    def <init>() = {
      super.<init>();
      ()
    };
    addConcreteType[A1]
  };
  TraitUnpickler$macro$1
})
```
The type arguments for A1 are completly missing which is the cause of the error.

**Comment by ochrons** [comment]
This really goes out of the scope of the macro helper, so I suggest you build the picklers using `CompositePickler` directly in this case. It's easy to come up with class hierarchies with type parameters that just cannot be automatically determined correctly, so I don't intend to support that in the macro any time soon :)

**Comment by FlorianKirmaier** [comment]
I'm not searching for not working class hierachies. Im switching from upickle to boopickle, and all of the cases I found did previously work with upickle. So there must be a way to solve it.
This is the last remaining incompatibility i have.

I found a way to solve this problem, but the solution is a bit tricky ... I will make a pull request for it so you can take a look on it.

Thank you for all of the quick responses and fixes.

**Comment by ochrons** [comment]
Yes, this particular case definitely can be done in the macro (by using Type instead of ClassSymbol when going through the hierarchy), but it might also create an impression that all kinds of type parameter configurations work ok, even when that is not the case. My macro code is based on Prickle, so some of the fancier stuff in uPickle is not supported at the moment.

If you can provide a PR, that would be great!

**Comment by FlorianKirmaier** [comment]
PR: https://github.com/ochrons/boopickle/pull/24
