### ISSUE TITLE
Is it worth it having Pickler & Unpickler separation?

### ISSUE THREAD

**Issue by japgolly** [ochrons/boopickle#28]
As mentioned [here](https://github.com/ochrons/boopickle#what-is-it-good-for), BooPickle is unlike other serialisation libraries in that the pickled (binary) data contains no general or  human-readable information indicative of structure or semantics.

`Pickler`s and `Unpickler`s must *always* be in sync or else the protocol fails.

Therefore is there any value in having separate `Pickler`s and `Unpickler`s instead of just a unified `Codec` or `Protocol`? Is there is *some* value is it enough to justify the downsides? Some of the downsides I'm noticing:

* Anytime you create a manual pickle, you need to repeat yourself twice. (`CompositePickler` + `CompositeUnpickler`, the `materializePickler` pair, etc.)
* Easy for pickle/unpickle to get out of sync. (especially as order matters so)

I can understand why it was separated originally but now that the library is being put to use, I'm thinking that this library and usage of it, would be greatly simplified by just having one typeclass instead of two.

**Comment by japgolly** [comment]
Ah, just as I write that I see there is a `PicklerPair` to avoid creating both `CompositePickler` and `CompositeUnpickler` manually. Curious that it is returned from `CompositePickler.apply` though.

But yeah, the point still stands. I think this library would be much nicer if everything was a `PicklerPair` - an approach I normally wouldn't suggest for other pickler libraries but I think would be good for BooPickle.

**Comment by ochrons** [comment]
This is a very good question indeed! The architecture was copied from Prickle, which in turn gets it from Scala pickling, so I didn't even consider that they might as well be combined :)

One potential downside is that the macro would then generate code for both pickling and unpickling even in the case where only one of them is needed.

**Comment by ochrons** [comment]
Give https://github.com/ochrons/boopickle/commit/b1eaafa7380d7c570d69de4679a2644343924eea a try :)

**Comment by japgolly** [comment]
I gave it a try. It's wonderful!!! Very nice and easy to use now! Thank you :beers:
