### ISSUE TITLE
Sync source maps and tagging scheme

### ISSUE THREAD

**Issue by japgolly** [ochrons/boopickle#3]
You've tagged the first release as `0.1.0`. Convention on most other projects I looked at (ages ago) is to have a `v` prefix, so `v0.1.0`. Accordingly, that's what the source maps are configured to point to. See https://github.com/ochrons/boopickle/blob/master/build.sbt#L56

1. I think you need to either prefix versions when you tags, or remove the prefix from SBT so they're in sync.
2. If 0.1.0 is out the door already, you should probably copy or rename the tag so that `v0.1.0` exists as it will already be compiled to expect it.

**Comment by ochrons** [comment]
Goot catch, I didn't consider this! I've added a v0.1.0 tag on the release, so it should work ok now.
