### ISSUE TITLE
Provide an example Play implementation

### ISSUE THREAD

**Issue by msatala** [ochrons/boopickle#38]
I'm trying to use boopickle in my Play framework project. However I quickly ran into troubles working with ByteBuffer in Play. I've searched github to find a project that is using boopickle with play framework, but I wasn't able to find anything. 

Could you please provide an example? AFAIK Play is the most popular scala framework so this would probably help a lot of potential users of this lib.

**Comment by ochrons** [comment]
Next version of my SPA tutorial will have Play and BooPickle. Here is a short snippet from that, showing how to integrate Autowire and BooPickle into Play controller with `ByteBuffers`.

```scala
  def autowireApi(path: String) = Action.async(parse.raw) {
    implicit request =>
      println(s"Request path: $path")
      // get the request body as Array[Byte]
      val b = request.body.asBytes(parse.UNLIMITED).get

      // call Autowire route
      Router.route[Api](apiService)(
        autowire.Core.Request(path.split("/"), Unpickle[Map[String, ByteBuffer]].fromBytes(ByteBuffer.wrap(b)))
      ).map(buffer => {
        val data = Array.ofDim[Byte](buffer.remaining())
        buffer.get(data)
        Ok(data)
      })
  }
```

**Comment by ochrons** [comment]
Latest SPA tutorial provides a good example for this.

**Comment by msatala** [comment]
Thank you!
