### ISSUE TITLE
Provide a way to configure the type of ByteBuffer

### ISSUE THREAD

**Issue by slandelle** [ochrons/boopickle#4]
Encoder currently uses direct ByteBuffers.

But like with most packing libraries, it's quite common to apply compression after packing.
Sadly, JDK's `Deflater` still doesn't support being passed a direct ByteBuffer, but only takes a byte array.
This forces users to do an additional array allocation + copy.

It could be great if Encoder could be more configurable, so one can easily override defaults and create his own `PickleState`.

**Comment by ochrons** [comment]
This is a good idea and requires only providing an optional "ByteBuffer factory" to the Encoder.

**Comment by slandelle** [comment]
You maybe don't even have to make it a factory. A `useDirectByteBuffer` boolean would probably suffice, and would be faster than a function (the JIT would be able to quickly eliminate dead branches).

**Comment by slandelle** [comment]
Please tell me what you think of my suggestion. I can then send a PR if you want.

**Comment by ochrons** [comment]
The factory architecture would also support building something like `ByteStrings` with multiple chained `ByteBuffers`. Currently if the buffer is too small and needs to be enlarged, a new buffer is allocated and previous data copied there. This is of course an issue only for rather large encodings that don't fit into the initial buffer.

**Comment by slandelle** [comment]
It really depends on what you're aiming with Boopickle and if you want to take MessagePack on ;-)

If you want to be able to deal with large payload (like, larger than 1kb,

**Comment by slandelle** [comment]
Nice! The new `BufferProvider` even let me write an implementation where I can recycle buffers, which is exactly what I need, thanks a lot!

Would it be possible for you to release 0.1.2?

**Comment by ochrons** [comment]
Fixed some other things, but now it's released!

**Comment by slandelle** [comment]
Great, thanks!

Can't wait to kill hundreds of loc on my side!

Still, I don't see 0.1.2 neither on [central](https://repo1.maven.org/maven2/me/chrons/boopickle_2.11/0.1.2/boopickle_2.11-0.1.2.pom) nor on [Sonatype](https://oss.sonatype.org/content/repositories/releases/me/chrons/boopickle_2.11/).

**Comment by ochrons** [comment]
Right, I forgot to release it on the Sonatype website. Now it should be out
there!

**Comment by slandelle** [comment]
Yep, it's here now. Thanks a lot!
