### ISSUE TITLE
websockets example

### ISSUE THREAD

**Issue by antonkulaga** [ochrons/boopickle#42]
Websockets require ArrayBuffer but I do not understand how I can turn bytebuffer form boopickler into either arraybuffer or blob that websocket wants, example in docs would be rather helpful.

**Comment by antonkulaga** [comment]
I managed to find a solution with 
```scala
import scala.scalajs.js.typedarray.TypedArrayBufferOps._
```
but it was not that straitforward to get there, so example will be helpful

**Comment by ochrons** [comment]
The conversion process used in the Ajax wrapper should work fine for Websocket as well. Note that if WS requires ArrayBuffer and does not accept a view (like Int8Array), then you might have to copy stuff around to get the subarray properly.

```scala
    def byteBuffer2ajax(data: ByteBuffer) = {
      if (data.hasTypedArray()) {
        // get relevant part of the underlying typed array
        data.typedArray().subarray(data.position, data.limit)
      } else {
        // fall back to copying the data
        val tempBuffer = ByteBuffer.allocateDirect(data.remaining)
        val origPosition = data.position
        tempBuffer.put(data)
        data.position(origPosition)
        tempBuffer.typedArray()
      }
    }
```

**Comment by antonkulaga** [comment]
Why did you close the issue? Sending bynary data over websockets is an important usecase and it is not described in docs
