### ISSUE TITLE
BigInt, BigDecimal support

### ISSUE THREAD

**Issue by guersam** [ochrons/boopickle#43]
As scala.js now has `BigInt` and `BigDecimal`, it'd be nice if boopickle has support for them.

**Comment by ochrons** [comment]
Want to do a quick PR for that? It should be quite trivial to pickle `BigInteger` as byte array and `BigDecimal` as `BigInteger` and its scale value.

**Comment by guersam** [comment]
I'm willing to do. just 4 bytes scale + bigint bytes should be ok.

**Comment by guersam** [comment]
Do we need to handle a special case in which the size of bigint part <= 4 bytes?

**Comment by ochrons** [comment]
And you can serialize the scale as `Int` which will be 1-5 bytes.

**Comment by guersam** [comment]
Oh, just found out that `writeInt` and `readInt` are already doing it for me. Thanks!
