### ISSUE TITLE
Incorrect results when pickling numeric strings in Scala.js

### ISSUE THREAD

**Issue by zlangbert** [ochrons/boopickle#48]
I am pickling numeric strings and I started to notice some were showing up on the server as totally different. After some investigating it seems (?) like 20 digit strings are not pickling/unpickling correctly in Scala.js. See below 

```scala
import boopickle.Default._
val numbers = Seq(0,1,2,3,4,5,6,7,8,9)
for (_ ← 0 until 10) {
  val s = Array.fill(20)(numbers(Random.nextInt(10))).mkString
  println(s)
  println(Unpickle[String].fromBytes(Pickle.intoBytes(s)))
  println("---------")
}
```

produces:

```
58213468898124653887
2873236676995999039
---------
45248643522829592471
8355155375410489239
---------
51496868058242682400
-3843364162885972448
---------
27982541370036899703
-8910946777382203529
---------
27492121753843503624
9045377680133952008
---------
15819678712131102020
-2627065361578449596
---------
50046200309684612602
-5294031911444042246
---------
36950005496042406970
56517348623303738
---------
32035983838405348908
-4857504309013754324
---------
33830692605305806048
-3062795542113297184
---------
```

Strings of length 19:
```
9220080788241269241
9220080788241269241
---------
7324346491285683657
7324346491285683657
---------
```

Strings of length 21:
```
725745014888300153818
725745014888300153818
---------
562803327751322974960
562803327751322974960
---------
```

**Comment by ochrons** [comment]
Thanks for reporting this. Probably related to the optimization in `String` pickler that recognizes numbers that would fit in a `Long` and encodes them as such, instead of a longer string. Perhaps the range check is not valid after all.

**Comment by ochrons** [comment]
I added a test case for this and indeed it works on the JVM but fails on JS. Maybe there is some issue with Longs in Scala.js after all.

**Comment by ochrons** [comment]
This is fixed in Scala.js master and will be included in the 0.6.6 release.

**Comment by zlangbert** [comment]
Okay great. Thank you!

**Comment by ochrons** [comment]
Boopickle is now updated to Scala.js 0.6.6 which fixes this bug,
