### ISSUE TITLE
Scala 2.12 milestones support

### ISSUE THREAD

**Issue by slandelle** [ochrons/boopickle#51]
Hi @ochrons 

Would it be possible to publish cross-built versions so projects depending on boopickle can give Scala 2.12 milestones a try, please?

Regards

**Comment by ochrons** [comment]
Sure, make a PR and I'll publish :)

**Comment by slandelle** [comment]
Cool, thanks!

**Comment by slandelle** [comment]
Mmm, sadly, that's not that simple. Boopickle is not an issue itself, but the test deps are: utest and nyaya are not cross-published for Scala 2.12.

That's a recurrent pattern: on every new major Scala versions, the test libs are on the critical path and lag behind :(

**Comment by ochrons** [comment]
Uh, looks like you'll have to convince @lihaoyi and @japgolly to cross-publish too :)

**Comment by slandelle** [comment]
Exactly :)
