### ISSUE TITLE
Performance and size differences - possible regression in 1.2.2

### ISSUE THREAD

**Issue by russwyte** [ochrons/boopickle#61]
I have observed since upgrading from 1.1.3 an exponential increase in pickling time (~ 1sec vs 1.5 minutes) of a map [String -> case class(simple strings and ints)] with around 350K members using the defaults for pickling/unpickling.

Also the size of the pickle roughly doubled.

Thank you for the pointers on the gitter channel.

Cheers!
Russ

**Comment by ochrons** [comment]
Yes, this was indeed an omission in the algorithm design, as it did not consider such high volumes of objects :)

This will be fixed in 1.2.3

**Comment by ochrons** [comment]
Fixed in release 1.2.3
