### ISSUE TITLE
Make EncoderSize non final

### ISSUE THREAD

**Issue by slandelle** [ochrons/boopickle#63]
Hi @ochrons 

Is there any reason why `EncoderSize` is final (`DecoderSize` isn't)?
I want to implement my own Int and Long encoding strategies, as I only deal with positive values, and would rather do so by extending existing classes. I currently can do that with the decoder size, but I have to copy-paste the encoder.

Cheers!

**Comment by ochrons** [comment]
It's probably something left over from the time there was only a single Encoder/Decoder. Now that there is a common trait, the `final` brings no performance benefits. Feel free to make a PR to make them all non-final.

**Comment by slandelle** [comment]
Great!

**Comment by slandelle** [comment]
Done #64

**Comment by slandelle** [comment]
Thanks!
