### ISSUE TITLE
Cannot materialize pickler for non-case class: Int. 

### ISSUE THREAD

**Issue by jozi-k** [ochrons/boopickle#65]
I am playing with this library and cannot pickle simple case class. My code looks like this:

```
import boopickle.Default._

case class Foo(a: Int)

object Main {
  def main(args: Array[String]) {
    val boo = Pickle.intoBytes(Foo(-1))
  }
}
```

But I get strange error: 
Cannot materialize pickler for non-case class: Int. If this is a collection, the error can refer to the class inside.
[error]     val booPickle = Pickle.intoBytes(Foo(1))
[error]                                     ^

What am I missing? Thanks for feedback.

**Comment by ochrons** [comment]
I had no trouble compiling the example you gave. Can you provide a reproducible example project?

**Comment by jozi-k** [comment]
Hi, 

I wanted to write simple stupid test for serializing and deserializing simple case class many times and compare multiple libraries (in this case scala-pickling, boopickle and our solution). But scala-pickling imports caused this error. When I removed those imports everything was fine. Thanks for quick hint @ochrons !

P.S. During the test of (de)serializing case class 10 million times, scala pickling v 0.11.0-M2 took 12s, your library 1,5s and our solution 0,018s so I assume we will stay with it for a while.

**Comment by ochrons** [comment]
Yeah, conflicting imports can cause that. As for the test results, you might want to check that your code actually does anything, instead of JVM optimizing it away or something, since that result would mean the (de)serialization to take only 6 CPU cycles on a 3.5GHz machine ;)

**Comment by jozi-k** [comment]
I am pretty sure you made mistake when computing CPU cycles number, my machine is far away from being 3.5GHz. See for yourself https://github.com/jozi-k/booPickle

P.S. Sure it does not handle fancy stuff that is in your library, but the speed is insane. And when you take in mind it is generated for each class that needs serialization, woila...

**Comment by ochrons** [comment]
Yes, for such straightforward case a custom code will naturally perform much better as BooPickle has all the overhead of allocating a new PickleState, Encoder and a ByteBuffer. For larger and more complex objects these costs get amortized, resulting in better performance.

BTW, I tested your code and it actually runs as fast when you remove the CustomCodec calls, so it seems JVM does optimize it away. Changing the data to `Foo(j)` instead of `Foo(-1)` prevents this. Also you should use `System.nanoTime()` for timing such loops, as it has much better accuracy.

**Comment by ochrons** [comment]
Out of general interest I added a straightforward `Seq[Foo]` serializer to your example and compared it to BooPickle. The performance difference was only 6x (not 50x as with a single `Foo`) when serializing a sequence of 50 `Foo`s.
