### ISSUE TITLE
converging with Prickle

### ISSUE THREAD

**Issue by antonkulaga** [ochrons/boopickle#9]
What I see is that boopickle is very similar to Prickle in terms of API but uses binary format instead of json one. I wonder is it possible to separate API from the format in a way that by changing one implicit I will be able to switch between json and binary and vice versa?

**Comment by Daxten** [comment]
that's more of a scala question, you have to define a trait for that

**Comment by ochrons** [comment]
The implementations are already diverging, so this is not going to work.
